language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t chentowsky/docker-react -f Dockerfile.dev .

#running the test
script:
    - docker run -e CI=true chentowsky/docker-react npm run test